# Generated by Django 4.1.1 on 2023-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablesAcquiring',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=1000, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tables_acquiring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesConstructor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('json', models.JSONField()),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tables_constructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('team1_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team2_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_image', models.CharField(blank=True, max_length=100, null=True)),
                ('second_image', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField()),
                ('header_image', models.CharField(blank=True, max_length=500, null=True)),
                ('top_event', models.BooleanField()),
                ('age', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=2000, null=True)),
                ('parsed_url', models.JSONField(blank=True, null=True)),
                ('fan_id', models.BooleanField(blank=True, null=True)),
                ('hidden', models.BooleanField(blank=True, null=True)),
                ('decrement', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tables_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesEventTags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tables_event_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesGallery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('show', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tables_gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesGenres',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tables_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesMargin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rules', models.JSONField()),
            ],
            options={
                'db_table': 'tables_margin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('header_text', models.CharField(max_length=200)),
                ('news_image', models.CharField(max_length=100)),
                ('main_text', models.TextField()),
                ('top_news', models.BooleanField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'tables_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('second_info', models.TextField()),
                ('order_info', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('ordered', models.BooleanField()),
                ('info', models.TextField()),
                ('ticket_ids', models.JSONField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('profit', models.JSONField()),
                ('utm', models.JSONField(blank=True, null=True)),
                ('mail_receipt', models.CharField(blank=True, max_length=500, null=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=500, null=True)),
                ('award', models.CharField(blank=True, max_length=50, null=True)),
                ('viewers', models.BooleanField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('fan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('punishment', models.IntegerField(blank=True, null=True)),
                ('site_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tables_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesOrdershistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(blank=True, max_length=500, null=True)),
                ('action', models.CharField(blank=True, max_length=500, null=True)),
                ('done_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tables_ordershistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesOwners',
            fields=[
                ('venue', models.CharField(max_length=200)),
                ('share1', models.FloatField()),
                ('share2', models.FloatField()),
                ('share3', models.FloatField()),
                ('share4', models.FloatField()),
                ('share5', models.FloatField()),
                ('from_date', models.CharField(blank=True, max_length=50, null=True)),
                ('to_date', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tables_owners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesParsedevents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('extra', models.JSONField()),
                ('url', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tables_parsedevents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesParsingtypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'tables_parsingtypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesPlaces',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tables_places',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesScenes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tables_scenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesSites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('actual_address', models.CharField(max_length=200)),
                ('inn', models.CharField(max_length=200)),
                ('legal_address', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('ogrnip', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('phone_common', models.CharField(max_length=200)),
                ('parsers', models.JSONField(blank=True, null=True)),
                ('reseller', models.BooleanField()),
                ('disabled', models.BooleanField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('sole_proprietor', models.CharField(blank=True, max_length=200, null=True)),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tables_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesSitesTags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tables_sites_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesStoredUrls',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('urls', models.JSONField()),
            ],
            options={
                'db_table': 'tables_stored_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesTags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'tables_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablesTickets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('sector', models.CharField(max_length=200)),
                ('sector_id', models.IntegerField()),
                ('row', models.CharField(max_length=200)),
                ('seat', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('original_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('operator', models.CharField(blank=True, max_length=200, null=True)),
                ('named', models.BooleanField(blank=True, null=True)),
                ('date_id', models.IntegerField(blank=True, null=True)),
                ('no_schema_available', models.IntegerField(blank=True, null=True)),
                ('own_bought', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tables_tickets',
                'managed': False,
            },
        ),
    ]
